In [1]:
import matplotlib.pyplot as plt
import sys
import time
import scipy.io as io
import os
from os import listdir
import glob
import time

import csv
import cv2
import numpy as np
from opt_flow import draw_flow

from scipy import ndimage as ndi

import math
from skimage import data
from skimage.filters import threshold_otsu
from skimage.segmentation import clear_border
from skimage.measure import label, regionprops
from skimage.morphology import binary_closing, binary_opening, binary_dilation, disk,remove_small_objects,label,binary_erosion
from skimage.color import label2rgb
from skimage import data, color, io, img_as_float

from scipy.signal import find_peaks
from skimage.filters import gaussian

import math
import pandas as pd

def listdir_nohidden(path):
    for f in os.listdir(path):
        if not f.startswith('.') and not f.startswith('contractivity'):
            yield f

def getLargestCC(segmentation):
    labels = label(segmentation)
    ###assert( labels.max() != 0 ) # assume at least 1 CC
    if labels.max()==0:
        return segmentation
    largestCC = labels == np.argmax(np.bincount(labels.flat)[1:])+1
    return largestCC

def SimilarityComparison(img10, img20):
    img1 = gaussian(img10, sigma=1)
    img2 = gaussian(img20, sigma=1)
   
    reg_hei,reg_wid = img10.shape
    
    N = reg_hei*reg_wid

    norm_term1 = np.sum(np.multiply(img1,img2))*N
    norm_term2 = np.sum(img1)*np.sum(img2)

    denorm_term1 = N*np.sum(np.multiply(img1,img1))-np.sum(img1)*np.sum(img1)
    denorm_term2 = N*np.sum(np.multiply(img2,img2))-np.sum(img2)*np.sum(img2)

    SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)
    
    return SC

def iPSC_pipeline(RootPath,OutputPath,subfolder):
    pass
    

    
    
    
ds = 2

RootPath = 'Y:\\RDRU_MYBPC3_2021\\Pilot20211011\\IPSC_Plate1'

OutputPath = 'Y:\\RDRU_MYBPC3_2021\\Pilot20211011_plate1_output'

subfolders = list(listdir_nohidden(RootPath))



In [4]:
for kk in range(2,100):
    subfolder = RootPath + "\\" + subfolders[kk]
    print(subfolder)

    if not os.path.exists(OutputPath):
        os.mkdir(OutputPath)
        print("Directory " , OutputPath ,  " Created ")
    else:    
        print("Directory " , OutputPath ,  " already exists")

    #subdirectories = os.listdir(RootPath)
    #videoNames = listdir(RootPath)
    ###videoNames = sorted(listdir(RootPath))
    videoNames = sorted(glob.glob(subfolder+"\\*.avi"))
    print(videoNames[0])
    ###videoNames = glob.glob(RootPath+"\\*.avi")
    ###print(videoNames)


    ############print(videoNames)

    imageNameRoot =  subfolder  + "\\tiff\\*.tif"
            #B9, C2,C4
    (dirName,videoFileName) = os.path.split(subfolder)

    imageNameRoot0 = dirName
    imageNames = sorted(glob.glob(imageNameRoot))
    imageNum = len(imageNames)


    print(dirName)
    ############print(imageNames[0])
    ############print('subfolder: ' + subfolder)
    ############print('ImageName: ' + str(imageNum))
    ############print('videoName: '+ str(videoFileName))

    img0 = cv2.imread(imageNames[0])
    ######frame10 = cv2.cvtColor(img0, cv2.COLOR_BGR2GRAY)
    ######
    ######ret, frame10 = cap.read()
    frame1 = img0[::ds,::ds,:]
    frame_ref = cv2.cvtColor(frame1,cv2.COLOR_BGR2GRAY)

    prvs = cv2.cvtColor(frame1,cv2.COLOR_BGR2GRAY)
    hsv = np.zeros_like(frame1)
    hsv[...,1] = 255


    hei, wid = prvs.shape

    magStack = np.zeros([hei, wid, int(imageNum)-1],dtype =  np.float32)
    angStack = np.zeros([hei, wid, int(imageNum)-1],dtype =  np.float32)
    SC_values_ref = np.zeros(int(imageNum)-1)


    for ii in range(1,imageNum-1):

        img2 = cv2.imread(imageNames[ii])
        frame20 = img2[::ds,::ds,:]
        frame2 = cv2.cvtColor(frame20,cv2.COLOR_BGR2GRAY)

        next = frame2

        SC_values_ref[ii-1] = SimilarityComparison(frame_ref, frame2)

        ### Gradient flow

        prvs_s = prvs
        next_s = next
        ##prvs_s = exposure.adjust_gamma(prvs_s, 1)
        ##next_s = exposure.adjust_gamma(next_s, 1)

        ##prvs_s = exposure.adjust_log(prvs, 5)
        ##next_s = exposure.adjust_log(next, 5)

        ###flow_d = next_s-prvs_s
        flow = cv2.calcOpticalFlowFarneback(prvs_s,next_s, None, .5, 3, 15, 3, 5, 1.2, 0)

        mag, ang = cv2.cartToPolar(flow[...,0], flow[...,1])
        hsv[...,0] = ang*180/np.pi/2
        hsv[...,2] = cv2.normalize(mag,None,0,255,cv2.NORM_MINMAX)
        hsv[...,2] = mag*10
        #print(np.max(mag))
        ###bgr = cv2.cvtColor(hsv,cv2.COLOR_HSV2BGR)
        ###vis = draw_flow(next_s, flow*10)

        magStack[:,:,ii] = mag

        if ii%100==0:
            print(ii)

        prvs = next


    speed = (np.gradient(SC_values_ref[:-20]))

    print(np.sum(np.isnan(speed)))
    maxSpeed = np.max(speed)
    minSpeed = np.min(speed)

    speed_Ind_pos, _ = find_peaks(speed, height= maxSpeed*0.7,distance=10)
    speed_Ind_neg, _ = find_peaks(-speed, height= -minSpeed*0.7,distance=10)

    maxHeight = np.max(1-SC_values_ref[:-20])
    dist_peak, _ = find_peaks(1-SC_values_ref[:-20], height= maxHeight*0.8,distance=100)


    fig, (ax1,ax2,ax3) = plt.subplots(3,1)

    ax1.plot(1-SC_values_ref[:-1])
    ax1.plot(dist_peak,1-SC_values_ref[dist_peak],"*")
    ###ax = plt.subplot(132)
    ax2.plot(speed)
    ax3.plot(abs(speed))
    ax3.plot(speed_Ind_pos,abs(speed[speed_Ind_pos]),"o")
    ax3.plot(speed_Ind_neg,abs(speed[speed_Ind_neg]),"x")
    ax3.plot(dist_peak,abs(speed[dist_peak]),"*")

    displayFigureName1 = OutputPath+"\\"+videoFileName+"_result1.png"
    print(displayFigureName1)
    fig.savefig(displayFigureName1)
    fig.clf()
    plt.close(fig)
    
    
    ###thresh = threshold_otsu(magSum)
    magSum = np.max(magStack,axis=2)
    thresh = np.percentile(magSum,80)
    mask = magSum>1*thresh

    cellMask1 = binary_closing(mask,disk(1))
    cellMask2 = ndi.binary_fill_holes(cellMask1)

    cellMask3 =  remove_small_objects(cellMask2,200)

    ###cellMask4 = cellMask3
    cellMask4 = binary_closing(cellMask3,disk(2))
    cellMask5 = ndi.binary_fill_holes(cellMask4)
    cellMask6 = binary_erosion(cellMask5,disk(1))
    cellMask7 = binary_opening(cellMask6,disk(3))

    cellMask8 =  remove_small_objects(cellMask7,400)

    cellMask9 = clear_border(cellMask8)

    cellMask9 = getLargestCC(cellMask9)

    mask_label = label(cellMask9)

    ###for ii in range(1,np.max(mask_label)):
    for jj in range(1,2):# just one object
        mask_region = (mask_label==jj)
        mask_region_stack = np.repeat(mask_region[:, :, np.newaxis], magStack.shape[2], axis=2)
        mask_region_size = np.sum(mask_region)
        print(mask_region_size)
        ##plt.imshow(mask_region_stack[:,:,200])
        magStack_mask = np.multiply(magStack, mask_region_stack.astype(int))
        flow_trace = np.sum(magStack_mask,axis=0)
        flow_trace = np.sum(flow_trace, axis=0)/mask_region_size


    A_list = []
    B_list = []

    half_width1 = 51 # related to sample freqency
    leftBound1 = dist_peak-half_width1
    rightBound1 = dist_peak+2

    half_width2 = 91 # related to sample freqency
    leftBound2 = dist_peak+10
    rightBound2 = dist_peak+half_width2


    for ii in range(len(leftBound1)):
        if leftBound1[ii]<5 or rightBound1[ii]>len(flow_trace)-20:
            continue

        maxV = np.max(flow_trace[leftBound1[ii]:rightBound1[ii]])
        neg_ind = leftBound1[ii]+np.argmax(flow_trace[leftBound1[ii]:rightBound1[ii]])
        A_list.append(neg_ind)

    for ii in range(len(leftBound2)):
        if leftBound2[ii]<5 or rightBound2[ii]>len(flow_trace)-20:
            continue

        maxV = np.max(flow_trace[leftBound2[ii]:rightBound2[ii]])
        pos_ind = leftBound2[ii]+np.argmax(flow_trace[leftBound2[ii]:rightBound2[ii]])
        B_list.append(pos_ind)

    As = np.array(A_list)
    Bs = np.array(B_list)
    print(As)
    print(Bs)

    fig, (ax1,ax2) = plt.subplots(2,1)
    plt.rcParams['figure.figsize'] = [18, 18]
            ###plt.subplot(211)

    alpha = 0.8
    img_hsv = color.rgb2hsv(frame1)
    color_mask = np.zeros(frame1.shape)
    color_mask[...,0] = cellMask9.astype(float)*255
    color_mask[...,1] = cellMask9.astype(float)*255
    #color_mask[...,2] = magMask.astype(np.float)*255
    color_mask_hsv = color.rgb2hsv(color_mask)

    img_hsv[..., 0] = color_mask_hsv[..., 0]
    img_hsv[..., 1] = color_mask_hsv[..., 1] * alpha
    img_masked = color.hsv2rgb(img_hsv)


    ax1.imshow(img_masked)
    ax2.plot(flow_trace[1:-10])
    ax2.plot(As,flow_trace[As], "x")
    ax2.plot(Bs,flow_trace[Bs], "d")
    ax2.plot(dist_peak,flow_trace[dist_peak],'*')
    ax2.plot(speed_Ind_pos,flow_trace[speed_Ind_pos],'*')
    ax2.plot(speed_Ind_neg,flow_trace[speed_Ind_neg],'*')
    
    displayFigureName2 = OutputPath+"\\"+videoFileName+"_result2.png"
    print(displayFigureName2)
    fig.savefig(displayFigureName2)
    fig.clf()
    plt.close(fig)
    
    

Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s003
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s003\211011_Brandon_IPSC_Plate1_s003_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s003_result1.png
2408
[ 36 181 282 379 454 552 694 816 891]
[106 216 335 402 552 616 727 891]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s003_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s004
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s004\211011_Brandon_IPSC_Plate1_s004_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s004_result1.png
3122
[374 426 577 688 743 864]
[426 562 605 738 841]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s004_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s005
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s005\211011_Brandon_IPSC_Plate1_s005_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s005_result1.png
2381
[294 433 579 725 869]
[327 468 610 754]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s005_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s006
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s006\211011_Brandon_IPSC_Plate1_s006_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s006_result1.png
452
[338 505 610 762 915]
[446 554 690 866]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s006_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s007
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s007\211011_Brandon_IPSC_Plate1_s007_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s007_result1.png
6038
[402 509 669 824 924]
[438 604 772 924]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s007_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s008
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s008\211011_Brandon_IPSC_Plate1_s008_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s008_result1.png
8131
[200 345 491 637 781 927]
[236 380 526 670 816]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s008_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s009
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s009\211011_Brandon_IPSC_Plate1_s009_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s009_result1.png
12775
[227 416 562 684 868]
[308 432 622 776]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s009_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s010
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s010\211011_Brandon_IPSC_Plate1_s010_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s010_result1.png
1191
[186 354 524 715 880]
[110 259 389 591 797]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s010_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s011
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s011\211011_Brandon_IPSC_Plate1_s011_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s011_result1.png
6817
[128 321 478 628 775 912]
[254 405 514 655 827]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s011_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s012
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s012\211011_Brandon_IPSC_Plate1_s012_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s012_result1.png
5177
[120 272 471 615 801]
[189 334 498 675 845]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s012_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s013
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s013\211011_Brandon_IPSC_Plate1_s013_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s013_result1.png
29749
[172 304 432 588 736 878]
[195 327 453 605 755]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s013_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s014
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s014\211011_Brandon_IPSC_Plate1_s014_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s014_result1.png
2293
[ 97 238 371 523 673 819]
[130 266 404 552 696 842]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s014_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s015
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s015\211011_Brandon_IPSC_Plate1_s015_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s015_result1.png
5125
[159 299 427 567 707 836]
[ 48 186 382 502 661 730]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s015_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s016
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s016\211011_Brandon_IPSC_Plate1_s016_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s016_result1.png
2251
[ 85 256 410 574 737 902]
[114 278 439 598 762]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s016_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s017
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s017\211011_Brandon_IPSC_Plate1_s017_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s017_result1.png
12361
[177 328 482 645 804]
[ 53 204 357 513 674 835]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s017_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s018
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s018\211011_Brandon_IPSC_Plate1_s018_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s018_result1.png
8027
[231 387 547 703 871]
[256 418 582 740]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s018_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s019
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s019\211011_Brandon_IPSC_Plate1_s019_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s019_result1.png
2043
[107 262 417 579 731 887]
[141 297 451 604 763]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s019_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s020
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s020\211011_Brandon_IPSC_Plate1_s020_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s020_result1.png
9787
[279 416 564 728 880]
[296 483 635 774]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s020_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s021
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s021\211011_Brandon_IPSC_Plate1_s021_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s021_result1.png
3357
[ 71 246 390 547 703 858]
[ 97 259 417 579 737]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s021_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s022
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s022\211011_Brandon_IPSC_Plate1_s022_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s022_result1.png
4933
[113 266 427 589 745 907]
[140 296 458 616 776]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s022_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s023
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s023\211011_Brandon_IPSC_Plate1_s023_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s023_result1.png
8752
[100 302 471 620 793 895]
[188 352 515 677 810]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s023_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s024
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s024\211011_Brandon_IPSC_Plate1_s024_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s024_result1.png
12831
[183 375 498 684 809]
[240 398 555 707 846]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s024_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s025
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s025\211011_Brandon_IPSC_Plate1_s025_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s025_result1.png
20715
[ 61 203 351 495 642 790]
[ 95 238 384 530 677 824]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s025_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s026
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s026\211011_Brandon_IPSC_Plate1_s026_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s026_result1.png
5121
[168 318 470 617 773 932]
[ 57 202 352 498 650 803]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s026_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s027
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s027\211011_Brandon_IPSC_Plate1_s027_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s027_result1.png
15224
[163 306 463 597 747 902]
[ 38 189 338 489 618 769]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s027_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s028
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s028\211011_Brandon_IPSC_Plate1_s028_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s028_result1.png
14331
[106 237 371 534 628 778 923]
[154 268 381 579 712 850]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s028_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s029
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s029\211011_Brandon_IPSC_Plate1_s029_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s029_result1.png
15371
[133 263 395 530 665 794]
[ 37 166 298 435 561 693 826]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s029_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s030
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s030\211011_Brandon_IPSC_Plate1_s030_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s030_result1.png
11808
[ 95 210 362 462 608 710 889]
[123 288 416 544 676 804]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s030_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s031
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s031\211011_Brandon_IPSC_Plate1_s031_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s031_result1.png
6759
[ 79 184 331 428 567 712 810]
[133 262 390 517 644 771]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s031_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s032
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s032\211011_Brandon_IPSC_Plate1_s032_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s032_result1.png
2197
[ 61 186 316 444 573 699 830]
[ 95 223 352 483 610 734 864]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s032_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s033
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s033\211011_Brandon_IPSC_Plate1_s033_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s033_result1.png
12959
[ 93 204 357 499 610 744 915]
[140 296 395 518 721 786]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s033_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s034
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s034\211011_Brandon_IPSC_Plate1_s034_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s034_result1.png
10051
[100 236 336 477 571 685 828]
[158 291 421 526 655 778]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s034_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s035
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s035\211011_Brandon_IPSC_Plate1_s035_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s035_result1.png
17088
[ 62 188 317 448 578 710 834]
[102 228 355 482 611 738 865]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s035_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s036
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s036\211011_Brandon_IPSC_Plate1_s036_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s036_result1.png
6099
[152 276 406 538 672 802 916]
[ 56 184 312 439 569 697 823]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s036_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s037
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s037\211011_Brandon_IPSC_Plate1_s037_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s037_result1.png
3596
[230 383 618 771]
[ 85 265 522 712 836]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s037_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s038
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s038\211011_Brandon_IPSC_Plate1_s038_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s038_result1.png
2667
[ 86 271 464 654 842]
[133 319 511 697 890]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s038_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s039
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s039\211011_Brandon_IPSC_Plate1_s039_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s039_result1.png
5567
[112 313 520 673 915]
[162 398 541 734]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s039_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s040
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s040\211011_Brandon_IPSC_Plate1_s040_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s040_result1.png
502
[ 48 239 434 628 816]
[ 92 284 479 672 862]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s040_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s041
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s041\211011_Brandon_IPSC_Plate1_s041_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s041_result1.png
10496
[ 92 320 560 788]
[130 368 591 819]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s041_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s042
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s042\211011_Brandon_IPSC_Plate1_s042_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s042_result1.png
23085
[ 63 175 389 480 559 713 836]
[140 271 413 517 612 836]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s042_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s043
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s043\211011_Brandon_IPSC_Plate1_s043_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s043_result1.png
9710
[ 59 318 639]
[106 365 688]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s043_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s044
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s044\211011_Brandon_IPSC_Plate1_s044_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s044_result1.png
10227
[338 589 828]
[381 634 878]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s044_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s045
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s045\211011_Brandon_IPSC_Plate1_s045_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s045_result1.png
847
[ 76 206 358 430 601 667 799 943]
[169 252 393 487 639 741 898]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s045_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s046
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s046\211011_Brandon_IPSC_Plate1_s046_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s046_result1.png
5979
[149 393 651 908]
[205 440 700]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s046_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s047
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s047\211011_Brandon_IPSC_Plate1_s047_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s047_result1.png
35945
[ 92 344 602 888]
[143 392 651]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s047_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s048
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s048\211011_Brandon_IPSC_Plate1_s048_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s048_result1.png
2624
[197 505 752]
[246 548 801]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s048_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s049
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s049\211011_Brandon_IPSC_Plate1_s049_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400
500
600
700
800
900


C:\Users\PANGJ05\AppData\Local\Temp\2/ipykernel_15460/1507772537.py:61: RuntimeWarning: invalid value encountered in double_scalars
  SC = (norm_term1-norm_term2)*(norm_term1-norm_term2)/(denorm_term1*denorm_term2)


0
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s049_result1.png
6863
[107 385 782]
[141 417 821]
Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output\211011_Brandon_IPSC_Plate1_s049_result2.png
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s050
Directory  Y:\RDRU_MYBPC3_2021\Pilot20211011_plate1_output  already exists
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1\211011_Brandon_IPSC_Plate1_s050\211011_Brandon_IPSC_Plate1_s050_video_ds.avi
Y:\RDRU_MYBPC3_2021\Pilot20211011\IPSC_Plate1
100
200
300
400


KeyboardInterrupt: 